[package]
name = "lights0123/llvm-spir"
version = "0.1.7"
entrypoint = "clang"

[fs]
"/lib/clang" = "./build/lib/clang"
"/sysroot" = "./em-sysroot-minimal"
"/hip" = "./hip"

[[module]]
name = "llvm"
source = "./llvm-opt-s-stripped.wasm"

[[command]]
name = "lld"
module = "llvm"
runner = "https://webc.org/runner/wasi"

[[command]]
name = "wasm-ld"
module = "llvm"
runner = "https://webc.org/runner/wasi"

[[command]]
name = "clang"
module = "llvm"
runner = "https://webc.org/runner/wasi"
[command.annotations.wasi]
env = ["PATH=/bin"]
exec-name = "clang"

[[command]]
name = "clang++"
module = "llvm"
runner = "https://webc.org/runner/wasi"

[[command]]
name = "clspv"
module = "llvm"
runner = "https://webc.org/runner/wasi"

[[command]]
name = "clspv-reflection"
module = "llvm"
runner = "https://webc.org/runner/wasi"

[[command]]
name = "spirv-tools-opt"
module = "llvm"
runner = "https://webc.org/runner/wasi"

[[command]]
name = "cxxfilt"
module = "llvm"
runner = "https://webc.org/runner/wasi"

[[command]]
name = "llvm"
module = "llvm"
runner = "https://webc.org/runner/wasi"
